### ISSUE TITLE
comparison and merging of base master and head master

### ISSUE THREAD

**Issue by dunnsurvey** [simonokeefe/NatureWest#1]
Hi Simon,

I have inadvertantly created an additional fork for friends-of-skeleton-creek data.  Request this additional data be incorporated into one source through comparison and merging of base master and head master data sets.

An opportunity to catch up with you to discuss new geojson developments and enhancement of community volunteer data collection would be appreciated.

Thanks

Wayne

**Comment by simonokeefe** [comment]
Hi Wayne,

I've just done a pull request and merge from your repo, which is what I think I'm meant to do for situations like this. Has this had the intended effect?

Happy to catch up again. I sometimes work from home on Fridays. I might be able to catch up around Werribe/Point Cook on Friday 16th.

**Comment by dunnsurvey** [comment]
Hi Simon,
                Thanks for your follow-up.  The merge has been successful with polyline and marker features now moved to dunnsurvey/NatureWest/master/friends-of-skeleton-creek project.  
The reason for my pull request: is - Although the Google spreadsheet component of NatureWest.pozi is updating. The spatial element from geojson/github are not being updated.  
Can you check the currency and validity of the spatial link between geojson/github and pozi (@ link below ) to see if you can ascertain the reason for the limited update of spatial elements.
https://go.pozi.com/#/e3lhrx.

I will be away overseas from Thur 15 Nov.  An opportunity to catch up on Fri 9 Nov or early December would be appreciated.  Venue and time in your hands.

Some questions for you then.
- Has there been any changes in the ability to add text to geojson markers
- Has the geospatial resolution of geojson been improved since our last discussion.  Or is Grant option the only avenue.
- Is there a smarter way to manage, render and display data by Calender Year in geojson.

Your support appreciated.

Thanks  Wayne

**Comment by dunnsurvey** [comment]
Hi Simon,
                Thanks for your follow-up.  The merge has been successful
with polyline and marker features now moved to
dunnsurvey/NatureWest/master/friends-of-skeleton-creek project.  Although
NatureWest.pozi displays the updated Google spreadsheet component; The
spatial element from geojson/github are partially updating;  This was the
reason for my pull request.
Can you check the currency and validity of the spatial link between
geojson/github and pozi liink @

**Comment by dunnsurvey** [comment]
Hi Simon, 
Thanks for your advice. 
I have now added missing FIDs to All geospatial features (polygons) and checked these updates have been saved to geojson_GitHub.  Can you check these updates on NatureWest.pozi.

Thanks

Wayne
